// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pie_backery.Models;

namespace pie_backery.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200212113414_create db")]
    partial class createdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("pie_backery.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Fruit pies",
                            Description = "All-fruity pies"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Cheese cakes",
                            Description = "All-cheesey pies"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Seasonal Pies",
                            Description = "All-seasonal pies"
                        });
                });

            modelBuilder.Entity("pie_backery.Models.Pie", b =>
                {
                    b.Property<string>("PieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AllergyInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Instock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPieOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pies");

                    b.HasData(
                        new
                        {
                            PieId = "1",
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://media.istockphoto.com/photos/whole-cherry-pie-picture-id535475493?k=6&m=535475493&s=612x612&w=0&h=yyG800xq7-noeZMUuCcSvieN_Pq7k_hY6y7AbISmz-s=",
                            ImageUrl = "https://media.istockphoto.com/photos/whole-cherry-pie-picture-id535475493?k=6&m=535475493&s=612x612&w=0&h=yyG800xq7-noeZMUuCcSvieN_Pq7k_hY6y7AbISmz-s=",
                            Instock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "Long long description",
                            Name = "Strawberry Pie",
                            Price = 15.95m,
                            ShortDescription = "Lorem Ipsum"
                        },
                        new
                        {
                            PieId = "2",
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://www.landolakes.com/RecipeManagementSystem/media/Recipe-Media-Files/Recipes/Retail/x17/16800-blue-ribbon-apple-pie-600x600.jpg?ext=.jpg",
                            ImageUrl = "https://www.landolakes.com/RecipeManagementSystem/media/Recipe-Media-Files/Recipes/Retail/x17/16800-blue-ribbon-apple-pie-600x600.jpg?ext=.jpg",
                            Instock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "Long long description",
                            Name = "Cheese Cake",
                            Price = 10.95m,
                            ShortDescription = "Lorem Ipsum"
                        },
                        new
                        {
                            PieId = "3",
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://ichef.bbci.co.uk/food/ic/food_16x9_832/recipes/chicken_pie_24044_16x9.jpg",
                            ImageUrl = "https://ichef.bbci.co.uk/food/ic/food_16x9_832/recipes/chicken_pie_24044_16x9.jpg",
                            Instock = false,
                            IsPieOfTheWeek = true,
                            LongDescription = "Long long description",
                            Name = "Rhubarb Pie",
                            Price = 11.95m,
                            ShortDescription = "Lorem Ipsum"
                        },
                        new
                        {
                            PieId = "4",
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2009/6/15/0/JI_20731_s4x3.jpg.rend.hgtvcom.826.620.suffix/1371589402748.jpeg",
                            ImageUrl = "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2009/6/15/0/JI_20731_s4x3.jpg.rend.hgtvcom.826.620.suffix/1371589402748.jpeg",
                            Instock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "Long long description",
                            Name = "Pumpkin Pie",
                            Price = 12.95m,
                            ShortDescription = "Lorem Ipsum"
                        });
                });

            modelBuilder.Entity("pie_backery.Models.Pie", b =>
                {
                    b.HasOne("pie_backery.Models.Category", "Category")
                        .WithMany("Pies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
